### ISSUE TITLE
# hiveserver 无法正常启动

### ISSUE THREAD

**Issue by Whojohn** [spancer/bigdata-docker-compose#1]
问题如下:

- 网络问题
1. 默认docker compose 启动会导致网络自带_default 。不同容器沟通时 如 : hiveserver -> database（刚开始连接的是hive-metabase 后续会返回 bigdata-docker-compose_default）, 会导致hive , hadoop异常。(通过绑定network 解决)。

- 数据库相关问题
1. 数据库初始化失败，具体请确认是否能够正常初始化？(pg不会玩)

**Comment by Whojohn** [comment]
ps: 搬运了好几人的镜像，是否说明下来源，并且测试是否能用呢？镜像是能启动，但是一堆问题。

**Comment by spancer** [comment]
网络问题：当然必须使用同一网络，因为所有服务之间的调用都是通过docker 构建的bridge网络，调用时采用docker-compose中定义的服务名。
数据库相关问题：PG的安装及脚本，都是采用官方的脚本。hive启动应该是没有问题，HBase应该有些问题，还在调试中。

**Comment by Whojohn** [comment]
- 网络问题
默认docker网络是不行的，原因是默认网络带有_default ，_ 符号是个非法符号 hadoop 相关的服务都会host异常！！！  
- hive 初始化
具体问题不清楚，你服务没有控制启动顺序，这个会导致初始化异常，可以参考别人的docker， 我已经找到可用的docker了。

**Comment by a2862433** [comment]
java连接 一直在报错 Caused by: java.net.UnknownHostException: can not resolve hbase-regionserver.bigdata-docker-compose_default,16020,1617873303577 啥原因啊？搞一天没搞出来

**Comment by pursue-wind** [comment]
`docker exec -it hive-server /bin/bash`
进入容器后执行sql后发现
FAILED: HiveException java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient

**Comment by spancer** [comment]
各位的错误无法重现，如有问题，可自行build 镜像。 相关脚本已开源： https://github.com/spancer/bigdata-docker-builds
