### ISSUE TITLE
hive-site.xml

### ISSUE THREAD

**Issue by wxyk** [spancer/bigdata-docker-compose#6]
hive-site.xml 是 on spark    改为 mr  还是跑不了  是什么原因呢

**Comment by spancer** [comment]
You may have to change hive-site.xml settings in both hive-metastore  & hive-server.  Hive on spark doesn't support yet because of my home's network error while uploading images. Alternative, you can use previous hive images instead.

hive-metastore:
    image: coomia/hive3.1-hadoop3.2:0.1
    container_name: hive-metastore
    volumes:
      - /data/tools:/tools
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 hive-metastore-pg:5432"
    ports:
      - "9083:9083"
  hive-metastore-pg:
    image: coomia/hive3.1-metastore-pg:0.1
    container_name: hive-metastore-pg
  hive-server:
    image: coomia/hive3.1-hadoop3.2:0.1
    container_name: hive-server
    env_file:
      - ./hadoop.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
