### ISSUE TITLE
在导入demo工程，下载jar包的时候，这几个jar包down不下来，都是带有${scala.binary.version}的

### ISSUE THREAD

**Issue by catxiong** [spancer/bigdata-docker-compose#9]
请问需要怎么解决了，谢谢！

Cannot resolve org.apache.flink:flink-connector-filesystem_2.12:1.12.2

**Comment by spancer** [comment]
> 

maven下包？换国内的maven公仓，或者直接下载相应的jar包，通过本地引用。
建议：与该项目不相关的问题，就不要在这提issue了。
